TRAIN:
  ENABLE: True
  DATASET: grasp
  BATCH_SIZE: 24
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
TEST:
  ENABLE: False
  DATASET: grasp
  BATCH_SIZE: 24
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 1
  TRAIN_JITTER_SCALES: [224, 320]
  TRAIN_CROP_SIZE: 224
  TRAIN_CROP_SIZE_LARGE: 356
  TEST_CROP_SIZE: 224
  TEST_CROP_SIZE_LARGE: 356
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  MAX_BBOXES: 5
  JUST_CENTER: False
ENDOVIS_DATASET:
  DETECTION_SCORE_THRESH: 0.0
  TRAIN_USE_COLOR_AUGMENTATION: True
  INCLUDE_GT: False
  USE_PREDS: True
MVIT:
  ZERO_DECAY_POS_CLS: False
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPOUT_RATE: 0.0
  DROPPATH_RATE: 0.4
  NORM: "layernorm"
  MODE: "conv"
  DEPTH: 16
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_KVQ_KERNEL: [3, 3, 3]
  SEP_POS_EMBED: True
  CLS_EMBED_ON: False
  FREEZE_PATCH: False
REGIONS:
  ENABLE: True
  ALIGNED: True
  ROI_XFORM_RESOLUTION: 3
  LEVEL: segmentation
AUG:
  ENABLE: False
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 1
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.125
  CLIP_GRAD_L2NORM: 1.0
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-2
  MAX_EPOCH: 50
  WARMUP_EPOCHS: 0.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  ZERO_WD_1D_PARAM: True
  WARMUP_START_LR:  0.0125
  OPTIMIZING_METHOD: sgd
MODEL:
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
  DECODER: True
  DECODER_HID_DIM: 2048
  DECODER_NUM_HEADS: 8
  DECODER_NUM_LAYERS: 1
  PRECISION: 32
TASKS:
  TASKS:  ["actions","instruments"]
  NUM_CLASSES: [14,7]
  LOSS_FUNC: ["bce","cross_entropy"]
  HEAD_ACT:  ["sigmoid","softmax"]
  LOSS_WEIGHTS:  [1.0,0.1]
  METRICS: ["mAP@0.5IoU_box","mAP@0.5IoU_segm"]
DATA_LOADER:
  NUM_WORKERS: 5
  PIN_MEMORY: True
FEATURES:
  ENABLE: True
  DIM_FEATURES: 256
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 10
OUTPUT_DIR: .