TRAIN:
  ENABLE: True
  DATASET: grasp
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 30
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TRAIN_CROP_SIZE_LARGE: 224
  TEST_CROP_SIZE: 224
  TEST_CROP_SIZE_LARGE: 224
  INPUT_CHANNEL_NUM: [3, 3]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
REGIONS:
  ENABLE: False
  ALIGNED: True
  ROI_XFORM_RESOLUTION: 3
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 11
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TASKS:
  TASKS:  ["phases"]
  NUM_CLASSES: [11]
  LOSS_FUNC: ["cross_entropy"]
  HEAD_ACT:  ["softmax"]
  LOSS_WEIGHTS:  [1.0] 
  METRICS: ["mAP"]  
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
FEATURES:
  ENABLE: False
TEST:
  ENABLE: True
  DATASET: grasp
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 5
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
