_BASE_: Base-GraSP-InstanceSegmentation.yaml
DATASETS:
  TRAIN_FOLD: "train"
  TEST_FOLD: "test"
  TRAIN: ("grasp_fold2",)
  TEST: ("grasp_fold1",)
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.0001
  STEPS: (2290, 4070)
  MAX_ITER: 4579