_BASE_: Base-GraSP-InstanceSegmentation.yaml
DATASETS:
  TRAIN_FOLD: "fold1"
  TEST_FOLD: "fold2"
  TRAIN: ("grasp_fold1",)
  TEST: ("grasp_fold2",)
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.0001
  STEPS: (2552, 4537)
  MAX_ITER: 5104